name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    # Roda apenas testes unitários (não dependem da API rodando)
    - name: Run unit tests
      run: npm run test:unit

    # Instala start-server-and-test para sincronizar API e testes externos
    - name: Install start-server-and-test
      run: npm install -g start-server-and-test

    # Sobe a API e roda os testes externos (que chamam localhost:4000)
    - name: Run external GraphQL tests
      run: start-server-and-test "node graphql/server.js" http://localhost:4000 "npm run test:external"
